### ISSUE TITLE
Windows are generated but can't see visuals !!!

### ISSUE THREAD

**Issue by Ajinkz** [SimLeek/cv_pubsubs#22] opened 2019-04-19 11:00 UTC
OS : window 7
Python 3.6.x

Webcam Logitech C110, C170

I'm using following code to see working of cvpubsubs library.

```
import cvpubsubs.webcam_pub as w
from cvpubsubs.window_sub import SubscriberWindows
t1 = w.VideoHandlerThread(0)
t2 = w.VideoHandlerThread(1)
t1.start()
t2.start()
SubscriberWindows(window_names=['cammy', 'cammy2'],
                  video_sources=[0,1]
                  ).loop()
t1.join()
t1.join()
```       
![thread](https://user-images.githubusercontent.com/11535456/56421447-27a6da80-62c0-11e9-9a65-97313af865de.JPG)

**Comment by SimLeek** [comment] 2019-05-01 17:54
Wait, how come github didn't notify me of this? I'll look into it once I get home.

**Comment by SimLeek** [comment] 2019-06-27 00:10
Can't reproduce. I did this with two numpy arrays and got this:

![image](https://user-images.githubusercontent.com/5911683/60223191-1258aa00-9835-11e9-8fd3-2de0083bdb55.png)

My webcams work with that syntax too.

Try setting high_speed to false if this still occurs. I'm closing this issue since it's too hardware specific for me to reproduce, or maybe I fixed it and forgot tot close this.

**Closed by SimLeek** 2019-06-27 00:10 UTC
